### ISSUE TITLE
undefined error when invoking grpc from a js callback

### ISSUE THREAD

**Issue by willemvermeer** [thesamet/AnyHike#1]
Hi, great work on ZIO-GRPC! I'm experimenting with AnyHike and my own code based on it. I found the following small problem. I'd like to do a grpc call from an onclick handler. It works, but I see an error message in the console.
To reproduce in AnyHike I added the following to WebappMain after line 54 with the three mouse events on canvas:
```scala
    rtGrpc <- ZIO.runtime[HikeStoreClient]
    _ <- ZIO.effectTotal {
      dom.document.getElementById("pad").addEventListener("click", {
        (e: MouseEvent) =>
          rtGrpc.unsafeRunSync {
            for {
              locs <- HikeStoreClient.getLocations(GetLocationsRequest())
              _ <- ZIO.effectTotal(dom.console.log(locs.toString))
            } yield true
          }})
    }
```
If you run this, it works and the locations are printed to the console as expected. However just prior to that console log an error is printed as well. It starts like this:
```
Uncaught Error: undefined
    $c_jl_Throwable webapp-fastopt.js:17669
    $c_jl_Error Throwables.scala:257
    get__O OneShot.scala:44
    $f_Lzio_Runtime__unsafeRunSync__F0__Lzio_Exit Runtime.scala:84
    anyhike$webapp$WebappMain$$$anonfun$appLogic$15__Lorg_scalajs_dom_raw_MouseEvent__Lzio_Runtime__Lzio_Exit WebappMain.scala:19
    2 WebappMain.scala:58
    addEventListener 
```
do you have any idea why this might be happening and how to prevent it? I tried a .catchAll on the call to getLocations but it's not happening.

**Comment by thesamet** [comment]
Does it happen when you invoke any other ZIO related thing inside the onclick handler?

**Comment by willemvermeer** [comment]
No. The following does not print any error:
```scala
    rtGrpc <- ZIO.runtime[HikeStoreClient]
    _ <- ZIO.effectTotal {
      dom.document.getElementById("pad").addEventListener("click", {
        (e: MouseEvent) =>
          rtGrpc.unsafeRunSync {
            for {
//              locs <- HikeStoreClient.getLocations(GetLocationsRequest())
              locs <- ZIO.succeed(GetLocationsResponse(Seq()))
              _ <- ZIO.effectTotal(dom.console.log(locs.toString))
            } yield true
          }})
    }
```
So the error only appears after/during a grpc invocation.

**Comment by willemvermeer** [comment]
Chrome gives a bit more error information:
```
Throwables.scala:18 Uncaught java.lang.Error: Cannot block for result to be set in JavaScript
    at $c_Lzio_internal_OneShot.get__O (http://localhost:8080/js/webapp-fastopt.js:13426:31)
    at $f_Lzio_Runtime__unsafeRunSync__F0__Lzio_Exit (http://localhost:8080/js/webapp-fastopt.js:12237:31)
    at $c_Lanyhike_webapp_WebappMain$.anyhike$webapp$WebappMain$$$anonfun$appLogic$15__Lorg_scalajs_dom_raw_MouseEvent__Lzio_Runtime__Lzio_Exit (http://localhost:8080/js/webapp-fastopt.js:36633:12)
    at HTMLCanvasElement.<anonymous> (http://localhost:8080/js/webapp-fastopt.js:36500:94)
```

**Comment by thesamet** [comment]
This actually makes sense - looks like it's coming from ZIO. The way the handler is written now, it's supposed to block the JS app until the result comes back, which is unlikely to be something that you want anyway. You need to find a way to break it to two parts so it can be done asyncly.

**Comment by willemvermeer** [comment]
Great, thanks for your quick comments!

**Comment by thesamet** [comment]
It looks like the way I got around this problem in this app was to push the mouse events into a queue, and then handle them through stream processing.
